# .goreleaser.yml
version: 2

project_name: go-let-loose

before:
  hooks:
    - go mod tidy

builds:
  - skip: true

# Generate checksum for the source code
checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

