# .goreleaser.yml
version: 2

project_name: go-let-loose

before:
  hooks:
    - go mod tidy

builds:
  - id: cli
    main: ./cmd/go-let-loose-cli/main.go
    binary: go-let-loose-cli
    flags:
      - -trimpath
    ldflags: -s -w -X main.Version={{ .Version }} -X main.CommitSHA={{ .Commit }}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

nfpms:
  - builds:
      - cli
    vendor: Moooooritz
    homepage: "https://moritz.biering.dev/"
    maintainer: "Moritz Biering <moritzbiering.mb@gmail.com>"
    description: "Go bindings and interface for the remote console of Hell Let Loose"
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

